import { Injectable } from '@angular/core';
import { Product } from './product';


@Injectable({
  providedIn: 'root'
})
export class InMemoryDataService {
  createDb() {
    const products = [
    {id: 1, name: 'Apple Watch S6', image: 'assets/apple/AppleWatchS644mm.jpg', company: 'Apple', type: '1',description: 'Apple Watch S6 LTE 44mm viền nhôm dây cao su xanh dương mang nét thanh lịch, các chi tiết được gia công chắc chắn, tinh xảo. Màn hình OLED 1.78 inch với thiết kế tràn viền giúp hình ảnh hiển thị rõ nét, chân thực. Nhờ có mặt kính Ion-X strengthened glass cứng cáp, chống trầy xước và chống va đập hiệu quả, đồng hồ an toàn trước những va chạm thường ngày. Dây đeo silicone êm nhẹ, độ đàn hồi cao, cho người dùng cảm giác dễ chịu suốt ngày dài.', price:'11.490.000'},
    {id: 2, name: 'Samsung Galaxy Watch Active 2', image: 'assets/samsung/samsung-galaxy-watch-active-2-44-mm-day-da-den-2-1-org.jpg', company: 'Samsung', type: '1',description: 'Đồng hồ thông minh Samsung Galaxy Watch Active 2 44mm là phiên bản có sự cải tiến về công nghệ để mang đến những trải nghiệm tốt nhất cho người dùng với nhiều tính năng chăm sóc sức khỏe, nhận cuộc gọi trực tiếp cũng như nhiều tính năng tiện ích khác. Đồn hồ có 7 chế độ tập luyện khác nhau. Đồng hồ thông minh Samsung Galaxy Watch Active 2 thực sự là huấn luyện viên thể thao chuyên nghiệp của bạn với việc tích hợp những chế độ luyện tập khác nhau cho phù hợp với cơ địa và thể trạng của từng người.', price:'9.990.000'},
    {id: 3, name: 'Xiaomi Watch S1', image: 'assets/xiaomi/xiaomiwatchs1den.jpg', company: 'Xiaomi', type: '1',description: 'Xiaomi Watch S1 là chiếc smartwatch mới nhất được nhà Xiaomi cho ra mắt, với diện mạo vô cùng thanh lịch được nâng cấp về mặt thiết kế cũng như tính năng so với thế hệ trước. Đồng hồ Xiaomi có độ hoàn thiện tinh tế được chế tác từ kính sapphire cao cấp có đường kính mặt 46.5 mm cùng khung viền thép tinh luyện chống ăn mòn và chống xước mang lại sự bền bỉ và khả năng chống chịu cực cao. Với đường kính mặt như thế này thì đồng hồ thích hợp với các bạn có cổ tay to hoặc các bạn nữ có kích thước cổ tay trung bình nhưng yêu thích sự cá tính, mạnh mẽ.', price:'5.990.000'},
    {id: 4, name: 'Huawei Watch GT3', image: 'assets/huawei/gt3.jpg', company: 'Huawei', type: '1',description: 'Thời lượng pin 14 ngày sử dụng thông thường. 8 ngày khi sử dụng thường xuyên. Theo dõi quá trình luyện tập với 100 chế độ được tích hợp sẵn. Chạy bộ chuyên nghiệp với huấn luyện viên AI cá nhân. Thiết kế thanh lịch với mặt kính cong 3D sang trọng.', price:'5.490.000'},
    {id: 5, name: 'Redmi Watch 2 Lite', image: 'assets/xiaomi/redmiwatchlite2.jpg', company: 'Xiaomi', type: '1',description: 'Redmi Watch 2 Lite sở hữu thiết kế màn hình lớn với kích thước 1.55 inch, tăng 10% diện tích so với bản tiền nhiệm Mi Watch Lite là 1.4 inch, được trang bị công nghệ màn hình TFT cùng độ phân giải 320 x 360 pixels hiển thị đa dạng màu sắc, hình ảnh rõ ràng, thoả mãn thị giác của bạn. Đồng thời, bạn có thể thay đổi giữa hơn 100 giao diện được thiết kế trong mặt đồng hồ tạo nên sự linh hoạt và đa dạng để phù hợp với trang phục hoặc tâm trạng mỗi ngày của bạn.', price:'1.190.000'},
    {id: 6, name: 'Xiaomi Watch S1 Active', image: 'assets/xiaomi/xiaomiwatchs1actve2.jpg', company: 'Xiaomi', type: '1',description: 'Vẫn mang một phong cách thiết kế năng động đậm chất thể thao nhưng được trang bị một màn hình có kích thước lớn hơn cùng việc hỗ trợ tần số quét 60 Hz, hệ điều hành MIUI được tuỳ biến riêng cho smartwatch, Xiaomi Watch S1 Active sẽ mang lại cho người dùng những trải nghiệm sử dụng mới mẻ hơn so với thế hệ tiền nhiệm. Watch S1 Active hướng đến hầu như mọi đối tượng và phong cách của người dùng, dù là cổ điển hay thanh lịch, nhân viên văn phòng hay dân chơi thể thao,... đều có thể sử dụng mẫu smartwatch này nhờ ngoại hình tối giản nhưng không kém cá tính với những đường cắt mạnh mẽ trên khung viền.', price:'4.490.000'},
    {id: 7, name: 'Mi Watch', image: 'assets/xiaomi/miwatch1org.jpg', company: 'Xiaomi', type: '1',description: 'Đồng hồ thông minh Mi Watch này mang phong cách trẻ trung, cá tính và đậm chất thể thao. Đồng hồ được trang bị công nghệ màn hình AMOLED với kích thước 1.39 inch cùng độ phân giải 454 x 454 pixels và độ sáng lên đến 450 nits giúp người dùng có thể quan sát thông tin rõ nét, chất lượng. Bên cạnh đó, đồng hồ còn được trang bị mặt kính cường lực Gorilla Glass 3 hạn chế trầy xước và tăng độ bền cho thiết bị. ', price:'1.745.000'},
    {id: 8, name: 'Mi Band 6', image: 'assets/xiaomi/miband612org.jpg', company: 'Xiaomi', type: '1',description: 'Vòng đeo tay thông minh Mi Band 6 là phiên bản đáng mong đợi của nhà Xiaomi với thiết kế màn hình tràn viền cho bạn góc nhìn tốt hơn. Mặt kính cường lực chống trầy xước tốt cùng dây đeo cao su với thiết kế ôm trọn cổ tay, không thấm nước khi đeo, mang lại cho bạn cảm giác dễ chịu cả ngày dài.', price:'949.000'},
    {id: 9, name: 'Samsung Galaxy Watch 4', image: 'assets/samsung/samsung-galaxy-watch-4-44mm-bac-1-org.jpg', company: 'Samsung', type: '1',description: 'Samsung Galaxy Watch 4 sở hữu thiết kế quen thuộc với khung viền nhôm bền bỉ, dây đeo silicone. Phiên bản 44mm này dành cho các chàng trai có cổ tay to nhưng vẫn giữ được nét thanh lịch vốn có nhờ kiểu thiết kế mặt đồng hồ tròn cổ điển. Ở lần ra mắt này, Samsung gây ấn tượng lớn với cộng đồng yêu thích công nghệ ở thế giới và Việt Nam khi trình làng chiếc đồng hồ thông minh đầu tiên sử dụng hệ điều hành Wear OS mới - One UI Watch, được tùy biến riêng cho thiết bị Samsung trên nền tảng cộng tác trực tiếp cùng Google.', price:'5.990.000'},
    {id: 10, name: 'Samsung Galaxy Watch 4 Classic', image: 'assets/samsung/samsung-galaxy-watch-4-44mm-bac-1.jpg', company: 'Samsung', type: '1',description: 'Điểm nhấn của Samsung Galaxy Watch 4 dòng Classic nằm ở thiết kế đậm nét cổ điển với những góc cạnh được vát tròn tinh tế. Vì thế, dù sở hữu đường kính mặt là 46 mm thì đồng hồ vẫn mang lại cảm giác gọn nhẹ, thanh lịch. Khung viền được chế tác từ thép không gỉ cao cấp chống ăn mòn hiệu quả, vòng xoay bezel vừa giúp người dùng định vị thời gian nhanh chóng với số phút được khắc ở mặt trong, vừa có tác dụng điều hướng thay thế cho các nút bấm bên cạnh đồng hồ. Dây đeo silicone có độ đàn hồi cao và thấm hút tốt khi tay ra mồ hôi.', price:'6.990.000'},
    {id: 11, name: 'Samsung Galaxy Watch 4 LTE Classic', image: 'assets/samsung/samsung-galaxy-watch-4-lte-classic-42mm1-org.jpg', company: 'Samsung', type: '1',description: 'Samsung Galaxy Watch 4 LTE Classic 42mm sở hữu thiết kế trẻ trung, hiện đại cùng khung viền thép không gỉ sang trọng, cứng cáp, lớp kính cường lực Gorrilla Glass Dx+ bảo vệ an toàn cho đồng hồ trước những va chạm thông thường. Dây đeo silicone mềm nhẹ, đàn hồi tốt, không thấm mồ hôi, cho cảm giác thoải mái khi mang.', price:'8.490.000'},
    {id: 12, name: 'Samsung Galaxy Watch 3 ', image: 'assets/samsung/samsung-galaxy-watch-3-41mm-vang-dong-1-org.jpg', company: 'Samsung', type: '1',description: 'Đồng hồ thông minh Samsung Galaxy Watch 3 41 mm sở hữu 2 nút bấm và vòng bezel xoay điều khiển vật lý, thay cho mặt xoay cảm ứng ở phiên bản Watch Active 2. Màn hình Super AMOLED 1.2 inch cùng độ phân giải 360 x 360 pixels giúp hình ảnh hiển thị được chân thật, rõ nét. Thân đồng hồ được làm bằng thép cứng cáp, khác với Watch Active 2 được làm bằng nhôm. Dây đeo chất liệu da tạo cảm giác chắc chắn và dễ chịu cho người dùng khi đeo.', price:'3.490.000'},
    {id: 13, name: 'Samsung Galaxy Fit2', image: 'assets/samsung/samsung-galaxy-fit2-den-1-2.jpg', company: 'Samsung', type: '1',description: 'Vòng tay thông minh Samsung là phụ kiện nhỏ gọn, hỗ trợ nhiều tính năng hiện đại đi kèm với giá thành rẻ hơn nhiều so với một chiếc SmartWatch. Trong đó, Samsung Galaxy Fit 2 là dòng sản phẩm mới ra gần đây, được cập nhật thêm các tính năng hữu ích và cải tiến thời lượng pin tới 15 ngày.', price:'750.000'},
    {id: 14, name: 'Apple Watch Series 7 LTE', image: 'assets/apple/AppleWatchSeries7LTE41mm.jpg', company: 'Apple', type: '1',description: 'Apple Watch S7 LTE 41 mm viền nhôm dây cao su có thiết kế được nâng cấp hơn so với phiên bản tiền nhiệm. Sở hữu vẻ ngoài sang trọng và hiện đại, Apple Watch S7 được thiết kế các góc bo tròn mềm mại với mặt đồng hồ được vác cong tạo cảm giác liền mạch hơn với khung viền. Phần khung viền được thiết kế mỏng hơn 40% và làm từ vật liệu nhôm tái chế 100% thân thiện với môi trường. Dây đeo cao su có độ đàn hồi tốt, thoải mái khi đeo và chống thấm mồ hôi hiệu quả.', price:'14.990.000'},
    {id: 15, name: 'Apple Watch SE', image: 'assets/apple/se-40mm-vien-nhom-day-cao-su-hong-glr-1-org.jpg', company: 'Apple', type: '1',description: 'Apple Watch SE 40mm viền nhôm dây cao su hồng có khung viền chắc chắn, thiết kế bo tròn 4 góc giúp thao tác vuốt chạm thoải mái hơn. Mặt kính cường lực Ion-X strengthened glass với kích thước 1.57 inch, hiển thị rõ ràng. Khung viền nhôm chắc chắn cùng dây đeo cao su có độ đàn hồi cao, êm ái, tạo cảm giác thoải mái khi đeo.', price:'7.490.000'},
    {id: 16, name: 'Apple Watch S5 LTE', image: 'assets/apple/s5-lte-40mm-vien-thep-day-thep-vang-glr-1-org.jpg', company: 'Apple', type: '1',description: 'Apple Watch S5 LTE 40mm viền thép dây thép vàng được trang bị bộ khung viền cứng cáp, dây đeo bằng thép dạng lưới đan mỏng tôn lên nét hiện đại, tinh tế. Đồng hồ sở hữu màn hình OLED 1.57 inch giúp hiển thị thông tin rõ ràng, sắc nét. Mặt kính cường lực Sapphire giúp bảo vệ đồng hồ an toàn trước những va chạm thường ngày.', price:'13.990.000'},
    {id: 17, name: 'Apple Watch Series 7 GPS', image: 'assets/apple/apple-watch-s7-45mm-gps-den-1.jpg', company: 'Apple', type: '1',description: 'Apple vừa cho ra mắt hàng loạt siêu phẩm khiến người dùng không khỏi trầm trồ, trong đó có chiếc Apple Watch S7 GPS 45 mm. Mẫu đồng hồ này mang vẻ ngoài tinh tế hơn với màn hình tràn viền và các góc được bo tròn mềm mại. Diện tích màn hình của đồng hồ tăng lên 20%, màn hình hiển thị được nhiều nội dung hơn, cụ thể là hơn 50% so với dòng S6 giúp người dùng nắm bắt thông tin một cách nhanh chóng mà không cần sử dụng thao tác vuốt nhiều lần. Trong lần ra mắt này, Apple trang bị cho dòng S7 khung viền bằng nhôm tái chế 100% giúp bảo vệ môi trường. Dây đeo silicone dẻo dai, không thấm nước mang lại cảm giác thoải mái, dễ chịu cho người dùng đặc biệt là những lúc tay đổ nhiều mồ hôi khi luyện tập thể thao.', price:'10.990.000'},
    {id: 18, name: 'Apple Watch S3 GPS', image: 'assets/apple/apple-watch-s3-gps-42mm-vien-nhom-day-cao-su-den-12-org.jpg', company: 'Apple', type: '1',description: 'Về mặt tổng thể Apple Watch S3 42 mm có kích thước tương tự như Apple Watch Series 2. Sản phẩm chú trọng thêm về mặt thẩm mỹ với thiết kế sang trọng, năng động, dây đeo có nhiều màu sắc khác nhau. Dây đeo của Apple Watch S3 GPS, 42mm viền nhôm được thiết kế với khả năng dễ dàng tháo rời, cho phép người dùng linh hoạt thay đổi bằng các dây đeo màu sắc khác. Đồng hồ thông minh Apple Watch phiên bản 42 mm có màn hình 1.65 inch hiển thị chi tiết ảnh nhiều hơn, mặt đồng hồ cảm ứng trang bị mặt kính cường lực Ion-X giúp bảo vệ mặt kính chống trầy xước tốt và hiển thị tốt dù là dưới ánh mặt trời.', price:'5.590.000'},
    {id: 19, name: 'Huawei Watch Fit', image: 'assets/huawei/HuaweiWatchFit.png', company: 'Apple', type: '1',description: 'ở hữu màn hình hiển thị lớn, đến 97 chế độ tập thể thao và nhiều tính năng đo sức khỏe suốt cả ngày, Huawei Watch Fit new chính là món phụ kiện góp phần làm nên chất lượng sống đầy linh hoạt và năng động dành cho bạn. Màn hình AMOLED cong 2.5D với loạt tùy biến. Đồng hồ thông minh Huawei Watch Fit new giúp bạn quan sát tốt nhất những dữ liệu hiển thị thông qua màn hình 1.64 inch hình chữ nhật độc đáo. Trang bị tấm nền AMOLED cùng mặt kính cong 2.5D, màn hình Fit new hiển thị chất lượng ảnh tuyệt đẹp. Tính năng tự động chỉnh sáng giúp bạn theo dõi nội dung ngoài trời tốt hơn, và mặt đồng hồ Always-on tùy biến cao sẽ giúp bạn thể hiện chất riêng cá nhân.', price:'1.690.000'},
    {id: 20, name: 'Huawei Band 6', image: 'assets/huawei/HuaweiBand6.jpg', company: 'Huawei', type: '1',description: 'Khác với đồng hồ thông minh, vòng đeo tay thông minh được giới hạn với những tính năng cần thiết. Tuy nhiên với những người dùng cơ bản không quá nặng về việc kết nối với smartphone thì đồng hồ Huawei Band 6 chính là ứng cử viên mà bạn đang tìm kiếm.', price:'899.000'},
    {id: 21, name: 'Huawei Watch 3', image: 'assets/huawei/Huaweiwatch3.png', company: 'Huawei', type: '1',description: 'Tiếp nối dòng sản phẩm tạm ngừng ở năm 2017, Huawei sẽ chuẩn bị cho ra mắt phiên bản smartwatch mới mang tên Huawei Watch 3. Sản phẩm này được hãng trang bị hệ điều hành mới với rất nhiều tính năng cao cấp. Chắc chắn chúng sẽ khiến người dùng phải đứng ngồi không yên.', price:'7.690.000'},
    {id: 22, name: 'Huawei Watch GT 2', image: 'assets/huawei/huawei-watch-gt2-46mm-day-da-400x400.jpg', company: 'Huawei', type: '1',description: 'Hãng công nghệ Huawei không chỉ chuyên về sản xuất điện thoại, mà còn mạnh về các sản phẩm phụ kiện hỗ trợ người dùng. Trong đó, Huawei Watch GT2 dây da sẽ là sản phẩm đồng hồ thích hợp cho các vận động viên, huấn luyện viên và những người yêu thể thao. Đồng hồ Huawei Watch GT 2 46mm dây da được thiết kế theo phong cách tối giản, phối hợp với chất liệu cao cấp mang đến vẻ ngoài thời thượng & lịch lãm trên tay bạn. Mặt kính 3D được chế tác tinh xảo tạo nên một bề mặt đồng hồ không viền đầy ấn tượng. Viền đồng hồ được làm từ chất liệu thép không gỉ cứng cáp, khẳng định nét sang trọng không thua gì đồng hồ cao cấp.', price:'3.690.000'},
    {id: 23, name: 'Huawei Watch 3 Pro', image: 'assets/huawei/dong-ho-thong-minh-huuawei-watch-3-pro-1.jpg', company: 'Huawei', type: '1',description: 'Tiếp tục là sản phẩm smartwatch đến từ thương hiệu Huawei, bộ đôi smartwatch mới Huawei Watch 3 và Huawei Watch 3 Pro được kế thừa nhiều ưu điểm của những người tiền nhiệm đi trước và được nâng cấp bởi công nghệ tân tiến hiện nay, hãy cùng xem liệu đồng hồ thông minh Huawei Watch 3 Pro có chinh phục được người dùng hay không? Hẳn các nhà thiết kế của Huawei cũng đã tìm hiểu rất kỹ về các sản phẩm đồng hồ đeo tay trước đó và dường như họ có cảm giác thân thiện hơn đối với mặt kính hình tròn. Ngay bên cạnh sườn của đồng hồ, có nút xoay tựa như Digital Crown.', price:'9.990.000'},
    {id: 24, name: 'Huawei Watch GT Runner', image: 'assets/huawei/HuaweiWatchGTRunner.png', company: 'Huawei', type: '1',description: 'Đồng hồ thông minh Huawei Watch GT Runner là sản phẩm được thiết kế dành riêng cho dân chuyên chạy bộ. Với hiệu suất anten GPS được cải thiện sẽ giúp các bạn có những trải nghiệm vô cùng độc đáo. Huawei Watch GT Runner sở hữu thiết kế thể thao vô cùng mạnh mẽ dành cho những vận động viên chạy bộ chuyên nghiệp. Thân đồng hồ được hoàn thiện từ sợi polyme bền bỉ cùng núm văn bằng hợp kim titan mang lại một thiết kế mạnh mẽ.', price:'6.490.000'},
    {id: 25, name: 'Huawei Watch GT 2 Pro', image: 'assets/huawei/HuaweiWatchGT2Pro.jpg', company: 'Huawei', type: '1',description: 'Là một sản phẩm mới được ra mắt cách đây chưa lâu nhưng đồng hồ thông minh Huawei Watch GT 2 Pro nhanh chóng thu hút được đông đảo người dùng bởi nhiều tính năng ấn tượng và hấp dẫn. Dưới đây là những thông tin chi tiết về chiếc đồng hồ thông minh mới nhất của Huawei này. Đồng hồ thông minh Huawei Watch GT 2 Pro là sản phẩm được sản xuất bởi thương hiệu đình đám trong giới công nghệ Huawei. Chiếc đồng hồ này có thiết kế khung titan, mặt sau gốm bóng mang đến sự cứng cáp và vô cùng bền bỉ.', price:'6.490.000'},
    {id: 26, name: 'Orient Star RE-AV0005L00B', image: 'assets/orient/re-av0005l-1.jpg', company: 'Orient', type: '2',description: ' Mẫu đồng hồ Nam RE-AV0005L00B đến từ hãng Orient của Nhật Bản. Thương hiệu nổi tiếng với các thiết kế thời thượng, sang trọng và quý phái. Phù hợp đeo hằng ngày và khi đi đến các sự kiện quan trọng. Đồng hồ cơ tự động (máy Automatic) có tuổi thọ cao, không lo hết pin, không cần lên dây cót thường xuyên, thời gian trữ cót khoảng 50 tiếng. Sở hữu đường kính mặt 41 mm, độ rộng dây 21 mm. Mặt kính sapphire cho độ sáng bóng cao, độ cứng cao, chịu lực tốt cùng với khả năng chống ăn mòn tuyệt đối. Dây làm bằng chất liệu da tổng hợp, khi đeo thoáng mát mềm mại trong ngày dài, dễ lau chùi và độ bền cao. Khung viền làm bằng kim loại có độ bền cao, chống ăn mòn, sáng bóng. ', price:'18.288.000'},
    {id: 27, name: 'Seiko SRP637K1', image: 'assets/seiko/dong-ho-seiko-srp637k1_1-ims.jpg', company: 'Seiko', type: '2',description: 'Trẻ trung, năng động, phong cách là những gì mà chiếc đồng hồ Seiko SRP637K1 mang đến cho phái mạnh. Bạn có thể kết hợp chiếc đồng hồ với những bộ trang phục hàng ngày để tạo lên phong cách riêng cho mình.', price:'9.810.000'},
    {id: 28, name: 'Citizen PC1003-58X', image: 'assets/citizen/pc1003-58x-1.jpg', company: 'Citizen', type: '2',description: 'Những chiếc đồng hồ Citizen chất lượng, bền bỉ và chuẩn xác nhưng lại gần gũi và phù hợp với bất kỳ đối tượng khách hàng nào. Từ một sinh viên, nhân viên văn phòng cho tới những người giàu sang đều hoàn toàn có thể lựa chọn những mẫu đồng hồ Citizen phù hợp. Đây chính là một trong những yếu tố mang tên tuổi thương hiệu Citizen ra đến toàn thế giới. Bên cạnh đó các mẫu thiết kế ngày càng đa dạng, thời trang, chất lượng liên tục được nâng cấp, nắm bắt được xu hướng. Một thương hiệu đồng hồ mang tầm ảnh hưởng đến thị trường thế giới đã làm cho người dân Nhật Bản vô cùng tự hào.', price:'12.500.000'},
    {id: 30, name: 'Candino C4708/3', image: 'assets/candino/candino-c4708-3-nam1-org.jpg', company: 'Candino', type: '2',description: 'Thương hiệu đồng hồ Candino được thành lập bởi Aldof Flury-Hug tại Bienne – nơi những chiếc đồng hồ Candino đầu tiên được sản xuất, là khu vực có đến một phần ba người dân sống bằng nghề sản xuất và chế tác đồng hồ. Vì vậy, nhắc tới Candino là nói về một thương hiệu với bề dày kinh nghiệm cũng như biểu tượng của giới nghệ nhân đồng hồ Thụy Sĩ.', price:'11.264.000'},
    {id: 29, name: 'candino-c4712-2-nam1-org', image: 'assets/candino/candino-c4712-2-nam1-org.jpg', company: 'Candino', type: '2',description: 'Thương hiệu đồng hồ Candino được thành lập bởi Aldof Flury-Hug tại Bienne – nơi những chiếc đồng hồ Candino đầu tiên được sản xuất, là khu vực có đến một phần ba người dân sống bằng nghề sản xuất và chế tác đồng hồ. Vì vậy, nhắc tới Candino là nói về một thương hiệu với bề dày kinh nghiệm cũng như biểu tượng của giới nghệ nhân đồng hồ Thụy Sĩ.', price:'10.808.000'},
    {id: 31, name: 'Candino C4706/1', image: 'assets/candino/candino-c4706-1-nam1-org.jpg', company: 'Candino', type: '2',description: 'Thương hiệu đồng hồ Candino được thành lập bởi Aldof Flury-Hug tại Bienne – nơi những chiếc đồng hồ Candino đầu tiên được sản xuất, là khu vực có đến một phần ba người dân sống bằng nghề sản xuất và chế tác đồng hồ. Vì vậy, nhắc tới Candino là nói về một thương hiệu với bề dày kinh nghiệm cũng như biểu tượng của giới nghệ nhân đồng hồ Thụy Sĩ.', price:'12.096.000'},
    {id: 32, name: 'Candino C4702/3', image: 'assets/candino/candino-c4702-3-nam1-org.jpg', company: 'Candino', type: '2',description: 'Thương hiệu đồng hồ Candino được thành lập bởi Aldof Flury-Hug tại Bienne – nơi những chiếc đồng hồ Candino đầu tiên được sản xuất, là khu vực có đến một phần ba người dân sống bằng nghề sản xuất và chế tác đồng hồ. Vì vậy, nhắc tới Candino là nói về một thương hiệu với bề dày kinh nghiệm cũng như biểu tượng của giới nghệ nhân đồng hồ Thụy Sĩ.', price:'12.096.000'},
    {id: 33, name: 'Candino C4702/1 ', image: 'assets/candino/candino-c4702-1-nam1-org.jpg', company: 'Candino', type: '2',description: 'Thương hiệu đồng hồ Candino được thành lập bởi Aldof Flury-Hug tại Bienne – nơi những chiếc đồng hồ Candino đầu tiên được sản xuất, là khu vực có đến một phần ba người dân sống bằng nghề sản xuất và chế tác đồng hồ. Vì vậy, nhắc tới Candino là nói về một thương hiệu với bề dày kinh nghiệm cũng như biểu tượng của giới nghệ nhân đồng hồ Thụy Sĩ.', price:'12.096.000'},
    {id: 34, name: 'Orient Star SDK05004K0', image: 'assets/orient/sdk05004k0-1.jpg', company: 'Orient', type: '2',description: 'Đồng hồ Orient đem đến những sản phẩm ấn tượng chinh phục người nhìn một cách nhanh chóng. Đồng hồ Orient với những chất liệu cao cấp bóng bẩy nâng tầm đẳng cấp cho người sở hữu, phù hợp với doanh nhân thành đạt, dân văn phòng hay các giám đốc công ty. Phong cách thời thượng, sang trọng đầy sức thu hút đến từ đồng hồ Orient chắc chắn sẽ khiến bạn luôn hãnh diện với những người xung quanh.', price:'14.706.000'},
    {id: 35, name: 'Orient Star SAF02005S0 ', image: 'assets/orient/saf02005s0-1.jpg', company: 'Orient', type: '2',description: 'Mẫu đồng hồ Nam SAF02005S0 đến từ hãng Orient của Nhật Bản. Thương hiệu nổi tiếng với các thiết kế thời thượng, sang trọng và quý phái. Phù hợp đeo hằng ngày và khi đi đến các sự kiện quan trọng. Đồng hồ cơ tự động (máy Automatic) có tuổi thọ cao, không lo hết pin, không cần lên dây cót thường xuyên, thời gian trữ cót khoảng 50 tiếng. Sở hữu đường kính mặt 41 mm, độ rộng dây 21 mm. Mặt kính sapphire cho độ sáng bóng cao, độ cứng cao, chịu lực tốt cùng với khả năng chống ăn mòn tuyệt đối. Dây làm bằng chất liệu da tổng hợp, khi đeo thoáng mát mềm mại trong ngày dài, dễ lau chùi và độ bền cao. Khung viền làm bằng kim loại có độ bền cao, chống ăn mòn, sáng bóng.', price:'10.296.000'},
    {id: 36, name: 'Orient Star RE-AV0B01S00B ', image: 'assets/orient/re-av0b01s00b-1.jpg', company: 'Orient', type: '2',description: 'Mẫu đồng hồ Nam RE-AV0B01S00B đến từ hãng Orient của Nhật Bản. Thương hiệu nổi tiếng với các thiết kế thời thượng, sang trọng và quý phái. Phù hợp đeo hằng ngày và khi đi đến các sự kiện quan trọng. Đồng hồ cơ tự động (máy Automatic) có tuổi thọ cao, không lo hết pin, không cần lên dây cót thường xuyên, thời gian trữ cót khoảng 50 tiếng. Sở hữu đường kính mặt 41 mm, độ rộng dây 21 mm. Mặt kính sapphire cho độ sáng bóng cao, độ cứng cao, chịu lực tốt cùng với khả năng chống ăn mòn tuyệt đối. Dây làm bằng chất liệu da tổng hợp, khi đeo thoáng mát mềm mại trong ngày dài, dễ lau chùi và độ bền cao. Khung viền làm bằng kim loại có độ bền cao, chống ăn mòn, sáng bóng.', price:'21.033.000'},
    {id: 37, name: 'Orient Star RE-AV0A04B00B', image: 'assets/orient/orient-star-re-av0a04b00b-nam-1.jpg', company: 'Orient', type: '2',description: 'Mẫu đồng hồ Nam RE-AV0A04B00B đến từ hãng Orient của Nhật Bản. Thương hiệu nổi tiếng với các thiết kế thời thượng, sang trọng và quý phái. Phù hợp đeo hằng ngày và khi đi đến các sự kiện quan trọng. Đồng hồ cơ tự động (máy Automatic) có tuổi thọ cao, không lo hết pin, không cần lên dây cót thường xuyên, thời gian trữ cót khoảng 50 tiếng. Sở hữu đường kính mặt 41 mm, độ rộng dây 21 mm. Mặt kính sapphire cho độ sáng bóng cao, độ cứng cao, chịu lực tốt cùng với khả năng chống ăn mòn tuyệt đối. Dây làm bằng chất liệu da tổng hợp, khi đeo thoáng mát mềm mại trong ngày dài, dễ lau chùi và độ bền cao. Khung viền làm bằng kim loại có độ bền cao, chống ăn mòn, sáng bóng.', price:'16.460.000'},
    {id: 38, name: 'Orient SK RA-AA0B02R19B', image: 'assets/orient/orient-ra-aa0b02r19b-nam-1.jpg', company: 'Orient', type: '2',description: 'Mẫu đồng hồ Nam RA-AA0B02R19B đến từ hãng Orient của Nhật Bản. Thương hiệu nổi tiếng với các thiết kế thời thượng, sang trọng và quý phái. Phù hợp đeo hằng ngày và khi đi đến các sự kiện quan trọng. Đồng hồ cơ tự động (máy Automatic) có tuổi thọ cao, không lo hết pin, không cần lên dây cót thường xuyên, thời gian trữ cót khoảng 50 tiếng. Sở hữu đường kính mặt 41 mm, độ rộng dây 21 mm. Mặt kính sapphire cho độ sáng bóng cao, độ cứng cao, chịu lực tốt cùng với khả năng chống ăn mòn tuyệt đối. Dây làm bằng chất liệu da tổng hợp, khi đeo thoáng mát mềm mại trong ngày dài, dễ lau chùi và độ bền cao. Khung viền làm bằng kim loại có độ bền cao, chống ăn mòn, sáng bóng.', price:'6.800.000'},
    {id: 39, name: 'Orient Star RE-AW0001B00B', image: 'assets/orient/orient-star-re-aw0001b00b-nam-1.jpg', company: 'Orient', type: '2',description: 'Mẫu đồng hồ Nam RE-AW0001B00B đến từ hãng Orient của Nhật Bản. Thương hiệu nổi tiếng với các thiết kế thời thượng, sang trọng và quý phái. Phù hợp đeo hằng ngày và khi đi đến các sự kiện quan trọng. Đồng hồ cơ tự động (máy Automatic) có tuổi thọ cao, không lo hết pin, không cần lên dây cót thường xuyên, thời gian trữ cót khoảng 50 tiếng. Sở hữu đường kính mặt 41 mm, độ rộng dây 21 mm. Mặt kính sapphire cho độ sáng bóng cao, độ cứng cao, chịu lực tốt cùng với khả năng chống ăn mòn tuyệt đối. Dây làm bằng chất liệu da tổng hợp, khi đeo thoáng mát mềm mại trong ngày dài, dễ lau chùi và độ bền cao. Khung viền làm bằng kim loại có độ bền cao, chống ăn mòn, sáng bóng.', price:'18.585.000'},
    {id: 40, name: 'Orient RF-QD0011L10B ', image: 'assets/orient/orient-rf-qd0011l10b-nam-glr-org.jpg', company: 'Orient', type: '2',description: 'Mẫu đòng hồ Nam RF-QD0011L10B đến từ hãng Orient của Nhật Bản. Thương hiệu nổi tiếng với các thiết kế thời thượng, sang trọng và quý phái. Phù hợp đeo hằng ngày và khi đi đến các sự kiện quan trọng. Đồng hồ cơ tự động (máy Automatic) có tuổi thọ cao, không lo hết pin, không cần lên dây cót thường xuyên, thời gian trữ cót khoảng 50 tiếng. Sở hữu đường kính mặt 41 mm, độ rộng dây 21 mm. Mặt kính sapphire cho độ sáng bóng cao, độ cứng cao, chịu lực tốt cùng với khả năng chống ăn mòn tuyệt đối. Dây làm bằng chất liệu da tổng hợp, khi đeo thoáng mát mềm mại trong ngày dài, dễ lau chùi và độ bền cao. Khung viền làm bằng kim loại có độ bền cao, chống ăn mòn, sáng bóng.', price:'3.100.000'},
    {id: 41, name: 'Seiko 5 SNK809K2', image: 'assets/seiko/dong-ho-seiko-5-snk809k2_1-ims.jpg', company: 'Seiko', type: '2',description: 'Trẻ trung, năng động, phong cách là những gì mà chiếc đồng hồ Seiko 5 SNK809K2 mang đến cho phái mạnh. Bạn có thể kết hợp chiếc đồng hồ với những bộ trang phục hàng ngày để tạo lên phong cách riêng cho mình.', price:'2.850.000'},
    {id: 42, name: 'Seiko SNZG09K1', image: 'assets/seiko/dong-ho-seiko-snzg09k1_1-ims.jpg', company: 'Seiko', type: '2',description: 'Trẻ trung, năng động, phong cách là những gì mà chiếc đồng hồ Seiko SNZG09K1 mang đến cho phái mạnh. Bạn có thể kết hợp chiếc đồng hồ với những bộ trang phục hàng ngày để tạo lên phong cách riêng cho mình.', price:'4.206.000'},
    {id: 43, name: 'Seiko SNZG15J1', image: 'assets/seiko/dong-ho-seiko-snzg15j1_1-ims.jpg', company: 'Seiko', type: '2',description: 'Trẻ trung, năng động, phong cách là những gì mà chiếc đồng hồ Seiko SNZG15J1 mang đến cho phái mạnh. Bạn có thể kết hợp chiếc đồng hồ với những bộ trang phục hàng ngày để tạo lên phong cách riêng cho mình.', price:'4.325.000'},
    {id: 44, name: 'Seiko SNZG13K1', image: 'assets/seiko/Seiko-SNZG13K1-1-1635220626449.jpg', company: 'Seiko', type: '2',description: 'Trẻ trung, năng động, phong cách là những gì mà chiếc đồng hồ Seiko SNZG13K1 mang đến cho phái mạnh. Bạn có thể kết hợp chiếc đồng hồ với những bộ trang phục hàng ngày để tạo lên phong cách riêng cho mình.', price:'4.376.000'},
    {id: 45, name: 'Seiko SNZG15K1', image: 'assets/seiko/SNZG15K1-1627374913659.jpg', company: 'Seiko', type: '2',description: 'Trẻ trung, năng động, phong cách là những gì mà chiếc đồng hồ Seiko SNZG15K1 mang đến cho phái mạnh. Bạn có thể kết hợp chiếc đồng hồ với những bộ trang phục hàng ngày để tạo lên phong cách riêng cho mình.', price:'4.206.000'},
    {id: 46, name: 'Seiko SPL059P1 LIMITED EDITION', image: 'assets/seiko/dong-ho-seiko-spl059p1_1-ims.jpg', company: 'Seiko', type: '2',description: 'Trẻ trung, năng động, phong cách là những gì mà chiếc đồng hồ Seiko SPL059P1 LIMITED EDITION mang đến cho phái mạnh. Bạn có thể kết hợp chiếc đồng hồ với những bộ trang phục hàng ngày để tạo lên phong cách riêng cho mình.', price:'7.425.000'},
    {id: 47, name: 'Citizen NH8396-82E', image: 'assets/citizen/dong-ho-citizen-nh8396-82e_1605259200.jpg', company: 'Citizen', type: '2',description: 'Những chiếc đồng hồ Citizen chất lượng, bền bỉ và chuẩn xác nhưng lại gần gũi và phù hợp với bất kỳ đối tượng khách hàng nào. Từ một sinh viên, nhân viên văn phòng cho tới những người giàu sang đều hoàn toàn có thể lựa chọn những mẫu đồng hồ Citizen phù hợp. Đây chính là một trong những yếu tố mang tên tuổi thương hiệu Citizen ra đến toàn thế giới. Bên cạnh đó các mẫu thiết kế ngày càng đa dạng, thời trang, chất lượng liên tục được nâng cấp, nắm bắt được xu hướng. Một thương hiệu đồng hồ mang tầm ảnh hưởng đến thị trường thế giới đã làm cho người dân Nhật Bản vô cùng tự hào.', price:'9.177.00'},
    {id: 48, name: 'Citizen NH8394-70H', image: 'assets/citizen/dong-ho-citizen-nh8394-70h_1605258633.jpg', company: 'Citizen', type: '2',description: 'Những chiếc đồng hồ Citizen chất lượng, bền bỉ và chuẩn xác nhưng lại gần gũi và phù hợp với bất kỳ đối tượng khách hàng nào. Từ một sinh viên, nhân viên văn phòng cho tới những người giàu sang đều hoàn toàn có thể lựa chọn những mẫu đồng hồ Citizen phù hợp. Đây chính là một trong những yếu tố mang tên tuổi thương hiệu Citizen ra đến toàn thế giới. Bên cạnh đó các mẫu thiết kế ngày càng đa dạng, thời trang, chất lượng liên tục được nâng cấp, nắm bắt được xu hướng. Một thương hiệu đồng hồ mang tầm ảnh hưởng đến thị trường thế giới đã làm cho người dân Nhật Bản vô cùng tự hào.', price:'9.177.000'},
    {id: 49, name: 'Citizen NH8390-20H', image: 'assets/citizen/dong-ho-citizen-nh8394-70h_1605258633.jpg', company: 'Citizen', type: '2',description: 'Những chiếc đồng hồ Citizen chất lượng, bền bỉ và chuẩn xác nhưng lại gần gũi và phù hợp với bất kỳ đối tượng khách hàng nào. Từ một sinh viên, nhân viên văn phòng cho tới những người giàu sang đều hoàn toàn có thể lựa chọn những mẫu đồng hồ Citizen phù hợp. Đây chính là một trong những yếu tố mang tên tuổi thương hiệu Citizen ra đến toàn thế giới. Bên cạnh đó các mẫu thiết kế ngày càng đa dạng, thời trang, chất lượng liên tục được nâng cấp, nắm bắt được xu hướng. Một thương hiệu đồng hồ mang tầm ảnh hưởng đến thị trường thế giới đã làm cho người dân Nhật Bản vô cùng tự hào.', price:'7.577.000'},
    {id: 50, name: 'Citizen EW2483-85B', image: 'assets/citizen/dong-ho-citizen-ew2483-85b-1_1588837663.jpg', company: 'Citizen', type: '2',description: 'Những chiếc đồng hồ Citizen chất lượng, bền bỉ và chuẩn xác nhưng lại gần gũi và phù hợp với bất kỳ đối tượng khách hàng nào. Từ một sinh viên, nhân viên văn phòng cho tới những người giàu sang đều hoàn toàn có thể lựa chọn những mẫu đồng hồ Citizen phù hợp. Đây chính là một trong những yếu tố mang tên tuổi thương hiệu Citizen ra đến toàn thế giới. Bên cạnh đó các mẫu thiết kế ngày càng đa dạng, thời trang, chất lượng liên tục được nâng cấp, nắm bắt được xu hướng. Một thương hiệu đồng hồ mang tầm ảnh hưởng đến thị trường thế giới đã làm cho người dân Nhật Bản vô cùng tự hào.', price:'6.336.500'},
    {id: 51, name: 'Citizen NH7514-59E', image: 'assets/citizen/dong-ho-citizen-nh7514-59e-1_1589187810.jpg', company: 'Citizen', type: '2',description: 'Những chiếc đồng hồ Citizen chất lượng, bền bỉ và chuẩn xác nhưng lại gần gũi và phù hợp với bất kỳ đối tượng khách hàng nào. Từ một sinh viên, nhân viên văn phòng cho tới những người giàu sang đều hoàn toàn có thể lựa chọn những mẫu đồng hồ Citizen phù hợp. Đây chính là một trong những yếu tố mang tên tuổi thương hiệu Citizen ra đến toàn thế giới. Bên cạnh đó các mẫu thiết kế ngày càng đa dạng, thời trang, chất lượng liên tục được nâng cấp, nắm bắt được xu hướng. Một thương hiệu đồng hồ mang tầm ảnh hưởng đến thị trường thế giới đã làm cho người dân Nhật Bản vô cùng tự hào.', price:'8.950.000'},

    ]
    return {products};
  }
  genId(products: Product[]): number {
    return products.length > 0 ? Math.max(...products.map(product => product.id)) + 1 : 11;
  }

  constructor() { }
}
